list.add(new Country("AF","Afghanistan"));
list.add(new Country("AX","Åland Islands"));
list.add(new Country("AL","Albania"));
list.add(new Country("DZ","Algeria"));
list.add(new Country("AS","American Samoa"));
list.add(new Country("AD","Andorra"));
list.add(new Country("AO","Angola"));
list.add(new Country("AI","Anguilla"));
list.add(new Country("AQ","Antarctica"));
list.add(new Country("AG","Antigua and Barbuda"));
list.add(new Country("AR","Argentina"));
list.add(new Country("AM","Armenia"));
list.add(new Country("AW","Aruba"));
list.add(new Country("AU","Australia"));
list.add(new Country("AT","Austria"));
list.add(new Country("AZ","Azerbaijan"));
list.add(new Country("BS","Bahamas"));
list.add(new Country("BH","Bahrain"));
list.add(new Country("BD","Bangladesh"));
list.add(new Country("BB","Barbados"));
list.add(new Country("BY","Belarus"));
list.add(new Country("BE","Belgium"));
list.add(new Country("BZ","Belize"));
list.add(new Country("BJ","Benin"));
list.add(new Country("BM","Bermuda"));
list.add(new Country("BT","Bhutan"));
list.add(new Country("BO","Bolivia, Plurinational State of"));
list.add(new Country("BQ","Bonaire, Sint Eustatius and Saba"));
list.add(new Country("BA","Bosnia and Herzegovina"));
list.add(new Country("BW","Botswana"));
list.add(new Country("BV","Bouvet Island"));
list.add(new Country("BR","Brazil"));
list.add(new Country("IO","British Indian Ocean Territory"));
list.add(new Country("BN","Brunei Darussalam"));
list.add(new Country("BG","Bulgaria"));
list.add(new Country("BF","Burkina Faso"));
list.add(new Country("BI","Burundi"));
list.add(new Country("KH","Cambodia"));
list.add(new Country("CM","Cameroon"));
list.add(new Country("CA","Canada"));
list.add(new Country("CV","Cape Verde"));
list.add(new Country("KY","Cayman Islands"));
list.add(new Country("CF","Central African Republic"));
list.add(new Country("TD","Chad"));
list.add(new Country("CL","Chile"));
list.add(new Country("CN","China"));
list.add(new Country("CX","Christmas Island"));
list.add(new Country("CC","Cocos (Keeling) Islands"));
list.add(new Country("CO","Colombia"));
list.add(new Country("KM","Comoros"));
list.add(new Country("CG","Congo"));
list.add(new Country("CD","Congo, the Democratic Republic of the"));
list.add(new Country("CK","Cook Islands"));
list.add(new Country("CR","Costa Rica"));
list.add(new Country("CI","Côte d'Ivoire"));
list.add(new Country("HR","Croatia"));
list.add(new Country("CU","Cuba"));
list.add(new Country("CW","Curaçao"));
list.add(new Country("CY","Cyprus"));
list.add(new Country("CZ","Czech Republic"));
list.add(new Country("DK","Denmark"));
list.add(new Country("DJ","Djibouti"));
list.add(new Country("DM","Dominica"));
list.add(new Country("DO","Dominican Republic"));
list.add(new Country("EC","Ecuador"));
list.add(new Country("EG","Egypt"));
list.add(new Country("SV","El Salvador"));
list.add(new Country("GQ","Equatorial Guinea"));
list.add(new Country("ER","Eritrea"));
list.add(new Country("EE","Estonia"));
list.add(new Country("ET","Ethiopia"));
list.add(new Country("FK","Falkland Islands (Malvinas)"));
list.add(new Country("FO","Faroe Islands"));
list.add(new Country("FJ","Fiji"));
list.add(new Country("FI","Finland"));
list.add(new Country("FR","France"));
list.add(new Country("GF","French Guiana"));
list.add(new Country("PF","French Polynesia"));
list.add(new Country("TF","French Southern Territories"));
list.add(new Country("GA","Gabon"));
list.add(new Country("GM","Gambia"));
list.add(new Country("GE","Georgia"));
list.add(new Country("DE","Germany"));
list.add(new Country("GH","Ghana"));
list.add(new Country("GI","Gibraltar"));
list.add(new Country("GR","Greece"));
list.add(new Country("GL","Greenland"));
list.add(new Country("GD","Grenada"));
list.add(new Country("GP","Guadeloupe"));
list.add(new Country("GU","Guam"));
list.add(new Country("GT","Guatemala"));
list.add(new Country("GG","Guernsey"));
list.add(new Country("GN","Guinea"));
list.add(new Country("GW","Guinea-Bissau"));
list.add(new Country("GY","Guyana"));
list.add(new Country("HT","Haiti"));
list.add(new Country("HM","Heard Island and McDonald Islands"));
list.add(new Country("VA","Holy See (Vatican City State)"));
list.add(new Country("HN","Honduras"));
list.add(new Country("HK","Hong Kong"));
list.add(new Country("HU","Hungary"));
list.add(new Country("IS","Iceland"));
list.add(new Country("IN","India"));
list.add(new Country("ID","Indonesia"));
list.add(new Country("IR","Iran, Islamic Republic of"));
list.add(new Country("IQ","Iraq"));
list.add(new Country("IE","Ireland"));
list.add(new Country("IM","Isle of Man"));
list.add(new Country("IL","Israel"));
list.add(new Country("IT","Italy"));
list.add(new Country("JM","Jamaica"));
list.add(new Country("JP","Japan"));
list.add(new Country("JE","Jersey"));
list.add(new Country("JO","Jordan"));
list.add(new Country("KZ","Kazakhstan"));
list.add(new Country("KE","Kenya"));
list.add(new Country("KI","Kiribati"));
list.add(new Country("KP","Korea, Democratic People's Republic of"));
list.add(new Country("KR","Korea, Republic of"));
list.add(new Country("KW","Kuwait"));
list.add(new Country("KG","Kyrgyzstan"));
list.add(new Country("LA","Lao People's Democratic Republic"));
list.add(new Country("LV","Latvia"));
list.add(new Country("LB","Lebanon"));
list.add(new Country("LS","Lesotho"));
list.add(new Country("LR","Liberia"));
list.add(new Country("LY","Libya"));
list.add(new Country("LI","Liechtenstein"));
list.add(new Country("LT","Lithuania"));
list.add(new Country("LU","Luxembourg"));
list.add(new Country("MO","Macao"));
list.add(new Country("MK","Macedonia, the former Yugoslav Republic of"));
list.add(new Country("MG","Madagascar"));
list.add(new Country("MW","Malawi"));
list.add(new Country("MY","Malaysia"));
list.add(new Country("MV","Maldives"));
list.add(new Country("ML","Mali"));
list.add(new Country("MT","Malta"));
list.add(new Country("MH","Marshall Islands"));
list.add(new Country("MQ","Martinique"));
list.add(new Country("MR","Mauritania"));
list.add(new Country("MU","Mauritius"));
list.add(new Country("YT","Mayotte"));
list.add(new Country("MX","Mexico"));
list.add(new Country("FM","Micronesia, Federated States of"));
list.add(new Country("MD","Moldova, Republic of"));
list.add(new Country("MC","Monaco"));
list.add(new Country("MN","Mongolia"));
list.add(new Country("ME","Montenegro"));
list.add(new Country("MS","Montserrat"));
list.add(new Country("MA","Morocco"));
list.add(new Country("MZ","Mozambique"));
list.add(new Country("MM","Myanmar"));
list.add(new Country("NA","Namibia"));
list.add(new Country("NR","Nauru"));
list.add(new Country("NP","Nepal"));
list.add(new Country("NL","Netherlands"));
list.add(new Country("NC","New Caledonia"));
list.add(new Country("NZ","New Zealand"));
list.add(new Country("NI","Nicaragua"));
list.add(new Country("NE","Niger"));
list.add(new Country("NG","Nigeria"));
list.add(new Country("NU","Niue"));
list.add(new Country("NF","Norfolk Island"));
list.add(new Country("MP","Northern Mariana Islands"));
list.add(new Country("NO","Norway"));
list.add(new Country("OM","Oman"));
list.add(new Country("PK","Pakistan"));
list.add(new Country("PW","Palau"));
list.add(new Country("PS","Palestinian Territory, Occupied"));
list.add(new Country("PA","Panama"));
list.add(new Country("PG","Papua New Guinea"));
list.add(new Country("PY","Paraguay"));
list.add(new Country("PE","Peru"));
list.add(new Country("PH","Philippines"));
list.add(new Country("PN","Pitcairn"));
list.add(new Country("PL","Poland"));
list.add(new Country("PT","Portugal"));
list.add(new Country("PR","Puerto Rico"));
list.add(new Country("QA","Qatar"));
list.add(new Country("RE","Réunion"));
list.add(new Country("RO","Romania"));
list.add(new Country("RU","Russian Federation"));
list.add(new Country("RW","Rwanda"));
list.add(new Country("BL","Saint Barthélemy"));
list.add(new Country("SH","Saint Helena, Ascension and Tristan da Cunha"));
list.add(new Country("KN","Saint Kitts and Nevis"));
list.add(new Country("LC","Saint Lucia"));
list.add(new Country("MF","Saint Martin (French part)"));
list.add(new Country("PM","Saint Pierre and Miquelon"));
list.add(new Country("VC","Saint Vincent and the Grenadines"));
list.add(new Country("WS","Samoa"));
list.add(new Country("SM","San Marino"));
list.add(new Country("ST","Sao Tome and Principe"));
list.add(new Country("SA","Saudi Arabia"));
list.add(new Country("SN","Senegal"));
list.add(new Country("RS","Serbia"));
list.add(new Country("SC","Seychelles"));
list.add(new Country("SL","Sierra Leone"));
list.add(new Country("SG","Singapore"));
list.add(new Country("SX","Sint Maarten (Dutch part)"));
list.add(new Country("SK","Slovakia"));
list.add(new Country("SI","Slovenia"));
list.add(new Country("SB","Solomon Islands"));
list.add(new Country("SO","Somalia"));
list.add(new Country("ZA","South Africa"));
list.add(new Country("GS","South Georgia and the South Sandwich Islands"));
list.add(new Country("SS","South Sudan"));
list.add(new Country("ES","Spain"));
list.add(new Country("LK","Sri Lanka"));
list.add(new Country("SD","Sudan"));
list.add(new Country("SR","Suriname"));
list.add(new Country("SJ","Svalbard and Jan Mayen"));
list.add(new Country("SZ","Swaziland"));
list.add(new Country("SE","Sweden"));
list.add(new Country("CH","Switzerland"));
list.add(new Country("SY","Syrian Arab Republic"));
list.add(new Country("TW","Taiwan, Province of China"));
list.add(new Country("TJ","Tajikistan"));
list.add(new Country("TZ","Tanzania, United Republic of"));
list.add(new Country("TH","Thailand"));
list.add(new Country("TL","Timor-Leste"));
list.add(new Country("TG","Togo"));
list.add(new Country("TK","Tokelau"));
list.add(new Country("TO","Tonga"));
list.add(new Country("TT","Trinidad and Tobago"));
list.add(new Country("TN","Tunisia"));
list.add(new Country("TR","Turkey"));
list.add(new Country("TM","Turkmenistan"));
list.add(new Country("TC","Turks and Caicos Islands"));
list.add(new Country("TV","Tuvalu"));
list.add(new Country("UG","Uganda"));
list.add(new Country("UA","Ukraine"));
list.add(new Country("AE","United Arab Emirates"));
list.add(new Country("GB","United Kingdom"));
list.add(new Country("US","United States"));
list.add(new Country("UM","United States Minor Outlying Islands"));
list.add(new Country("UY","Uruguay"));
list.add(new Country("UZ","Uzbekistan"));
list.add(new Country("VU","Vanuatu"));
list.add(new Country("VE","Venezuela, Bolivarian Republic of"));
list.add(new Country("VN","Viet Nam"));
list.add(new Country("VG","Virgin Islands, British"));
list.add(new Country("VI","Virgin Islands, U.S."));
list.add(new Country("WF","Wallis and Futuna"));
list.add(new Country("EH","Western Sahara"));
list.add(new Country("YE","Yemen"));
list.add(new Country("ZM","Zambia"));
list.add(new Country("ZW","Zimbabwe"));